theme: jekyll-theme-minimal
title: Caitlin Settles
description: Computer engineering student at California Polytechnic University, San Luis Obispo.

# Social
github_url: https://github.com/csettles
linked_in: https://www.linkedin.com/in/caitlin-settles-a60766aa/
email_link: mailto:csettles@calpoly.edu
github_svg: https://img.shields.io/github/followers/espadrine.svg?style=social&label=Follow

