theme: jekyll-theme-minimal
title: Caitlin Settles
description: Computer engineering studedent at California Polytechnic University, San Luis Obispo.

# Social
github: https://github.com/csettles
linked_in: https://www.linkedin.com/in/caitlin-settles-a60766aa/
email_link: mailto:csettles@calpoly.edu

